set(
    INCLUDE_H
    include/carl/vm/vm.h
    include/carl/vm/chunk.h
    include/carl/vm/memory.h
    include/carl/vm/env.h
    include/carl/ast/type_inference.h
    include/carl/ast/print_visitor.h
    include/carl/ast/ast_printer.h
    include/carl/ast/ast.h
    include/carl/ast/types.h
    include/carl/basic_codegen.h
    include/carl/llvm/codegen.h
    include/carl/llvm/jit.h
    include/carl/scanner.h
    include/carl/parser.h
    include/carl/common.h
)